### ISSUE TITLE
火绒内存查杀

### ISSUE THREAD

**Issue by Fly-VX** [lv183037/MaLoader#1]
大佬简单测试了一下，几种方式都能上线火绒，但只要执行命令之类的任何操作都会被内存查杀，目前我所知道绕过火绒内存查杀最简单的是可以采用远程线程注入
![image](https://github.com/user-attachments/assets/ecd7fad7-6c1b-42ba-9135-ffc0061a45f5)

**Comment by lv183037** [comment]
可以配合arsenal-kit套件，可参考 https://xz.aliyun.com/t/14798
